"""add unique constraint to user_id in students and teachers

Revision ID: d25eef2edde7
Revises: e6e2723c3e61
Create Date: 2026-07-29 23:57:39.179531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25eef2edde7'
down_revision: Union[str, Sequence[str], None] = 'e6e2723c3e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'birth_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.create_unique_constraint(None, 'teachers', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='unique')
    op.drop_constraint(None, 'students', type_='unique')
    op.alter_column('students', 'birth_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
