"""add unique constraint to user_id in students and teachers

Revision ID: d25eef2edde7
Revises: e6e2723c3e61
Create Date: 2026-07-29 23:57:39.179531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd25eef2edde7'
down_revision: Union[str, Sequence[str], None] = 'e6e2723c3e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students') as batch_op:
        batch_op.alter_column(
            'birth_date',
            existing_type=sa.DATETIME(),
            type_=sa.Date(),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(
            'uq_students_user_id',
            ['user_id'],
        )

    with op.batch_alter_table('teachers') as batch_op:
        batch_op.create_unique_constraint(
            'uq_teachers_user_id',
            ['user_id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers') as batch_op:
        batch_op.drop_constraint('uq_teachers_user_id', type_='unique')

    with op.batch_alter_table('students') as batch_op:
        batch_op.drop_constraint('uq_students_user_id', type_='unique')
        batch_op.alter_column(
            'birth_date',
            existing_type=sa.Date(),
            type_=sa.DATETIME(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
